#!/usr/bin/env bash
# Script to display the content of /etc/passwd in a story format, following ShellCheck guidelines

while IFS=':' read -r username password gid uid info home shell; do
    echo "The user $uernameis part of the $gid gang,"\
	   "lives in $home and rides $shell."\
	   "$uid's place is protected by the passcode $password,"\
	  " more info about the user here: $user_info"
done < /etc/passwd

