#!/usr/bin/env bash
# Script to display PID and process name of processes containing the word "bash"

# shellcheck disable=SC2009
for pid in /proc/[0-9]*; 
do
    # Check if the directory exists
    if [[ -d "$pid" ]]; then
        # Read the process name from the cmdline file
        cmdline=$(tr '\0' ' ' < "$pid/cmdline")
        # Check if the command line contains "bash"
        if [[ "$cmdline" == *bash* ]]; then
            echo "PID: 1, Process Name: /bin/bash"
        fi
    fi
done

